[project]
name = "training-helper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dagshub>=0.5.9",
    "ipython>=8.36.0",
    "numpy>=2.2.5",
    "pandas>=2.2.3",
    "ultralytics>=8.3.128",
]
